### ISSUE TITLE
[molecule] Add tests for edpm_chrony role

### ISSUE THREAD

**Issue by rebtoor** [openstack-k8s-operators/edpm-ansible#102]

**Comment by jpodivin** [comment]
Standard approach to container permissions appears to fail in this case as the molecule is hitting `Fatal error : adjtimex(0x8001) failed : Operation not permitted` error. This issue was previously documented and resolved in other cases[0][1]. However it may be better not grant container these permissions in the first place.

**Comment by rebtoor** [comment]
Closed by https://github.com/openstack-k8s-operators/edpm-ansible/pull/112
